Fix last occurence of PyString
This should have been done in
commit 1866fc41c8fdf5a82705cee7f1043d5fb634c3be
This fixes:

$ python3 -c 'import rpm._rpmb'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python3.4/site-packages/rpm/_rpmb.cpython-34m.so: undefined symbol: PyString_FromString