Check for file conflicts in installed packages
- Rpm checks that a conflict in the new package is not satisfied by an
  installed file, but it ignores when a conflict of an installed package
  is satisfied by a file of the new package, eg

    Package A: Contains file "/foo"
    Package B: Has "Conflicts: /foo"

    rpm -U A.rpm, then rpm -U B.rpm results in:
    error: Failed dependencies:
        /foo conflicts with B-1-1.i586

    rpm -U B.rpm, then rpm -U A.rpm will work.
- Use an IndexIterator over RPMTAG_CONFLICTNAME to create a hash with
  all of the possible file conflicts to speed things up.
Signed-off-by: Panu Matilainen <pmatilai@redhat.com>